---
- hosts: [WPVM]
  become: yes
  tasks:
    - name: Clone WordPress repo
      ansible.builtin.git:
        repo: https://github.com/issamelferkh/wp_auto_deploy.git
        dest: /home/issam/cloud_1

    - name: Create Data folder for volumes if not exist
      ansible.builtin.file:
        path: /home/issam/data
        owner: issam
        group: issam
        state: directory
        mode: '0755'

    - name: Create Data folder for volumes if not exist
      ansible.builtin.file:
        path: /home/issam/data/DB
        owner: issam
        group: issam
        state: directory
        mode: '0755'

    - name: Create Data folder for volumes if not exist
      ansible.builtin.file:
        path: /home/issam/data/WordPress
        owner: issam
        group: issam
        state: directory
        mode: '0755'

    - name: Execute run script to deploy wp docker containers
      shell:
        chdir: /home/issam/cloud_1/wordpress/
        cmd: "chmod +x run.sh"
        cmd: "./run.sh"
      # ansible.builtin.shell: /home/issam/cloud_1/wordpress/run.sh >> somelog.txt