# WordPressResourceGroup Resource Group
WordPressResourceGroupName: WordPressResourceGroup1

# Create Virtual Network (VNet)
WP_VnetName: WP_Vnet1

# Add subnet (VSubNet)
WP_SubnetName: WP_Subnet1

# Create Public IP address (IP)
WP_PublicIPName: WP_PublicIP1

# Create Network Security Group that allows SSH (NSG)
WP_NSGName: WP_NSG1

# Create Virtual Network Interface Card (NIC)
WP_NICName: WP_NIC1

# WordPress Virtual Machine WPVM
VMname: WPVM1
VM_admin_username: issam
VM_admin_password: issam123!