version: "3.5"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    networks:
      - inception-network
    ports:
      - "443:443"
    volumes:
      - /home/obouykou/data/wp:/www/wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    networks:
      - inception-network
    volumes:
      - /home/obouykou/data/wp:/www/wordpress
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${MYSQL_USER_USERNAME}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_USER_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    networks:
      - inception-network
    volumes:
      - /home/obouykou/data/db:/var/lib/mysql
    depends_on:
      - wordpress
    environment:
      MYSQL_USER_USERNAME: "${MYSQL_USER_USERNAME}"
      MYSQL_USER_PASSWORD: "${MYSQL_USER_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    restart: always

  ftp:
    container_name: ftp
    build: requirements/bonus/ftp
    image: ftp
    networks:
      - inception-network
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "10100:10100"
    volumes:
      - /home/obouykou/data/wp:/home/obouykou
    environment:
      FTP_USERNAME: "${FTP_USERNAME}"
      FTP_PASSWORD: "${FTP_PASSWORD}"
    restart: always

  redis:
    container_name: redis
    build: requirements/bonus/redis
    image: redis
    networks:
      - inception-network
    ports:
      - "6379:6379"
    depends_on:
      - wordpress
    volumes:
      - /home/obouykou/data/wp:/www/wordpress
    restart: always

  adminer:
    container_name: adminer
    build: requirements/bonus/adminer
    image: adminer
    networks:
      - inception-network
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "8080:8080"
    restart: always

  website:
    container_name: website
    build: requirements/bonus/website
    image: website
    networks:
      - inception-network
    ports:
      - "8090:8090"
    restart: always

  backup:
    container_name: backup
    build: requirements/bonus/backup
    image: backup
    networks:
      - inception-network
    depends_on:
      - mariadb
    volumes:
      - /home/obouykou/data/db:/db_volume
      - /home/obouykou/data/backup:/backup
    restart: always

networks:
  inception-network:
    name: "inception-net"
