- name: Remove a VM
  hosts: localhost
  gather_facts: no
  tasks: 

  - name: Remove a VM and all resources that were autocreated
    azure_rm_virtualmachine:
      resource_group: "{{ WordPressResourceGroupName }}"
      name: "{{ VMname }}"
      remove_on_absent: all_autocreated
      state: absent
