- name: Allow SSH
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Create Network Security Group that allows SSH (NSG)
    azure_rm_securitygroup:
      resource_group: "{{ WordPressResourceGroupName }}"
      name: "{{ WP_NSGName }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound

- name: Auto Deploy WP
  hosts: [WPVM]
  gather_facts: no
  become: yes
  tasks:
    - name: Update WPVM OS
      command: apt update -y 

    - name: Install python3
      package:
       name: python3
       state: present

    - name: Install docker
      apt:
        name: python3-pip, docker.io, docker-compose
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Install docker python module
      pip:
        name: docker

    - name: Clone WordPress repo
      ansible.builtin.git:
        repo: https://github.com/issamelferkh/wp_auto_deploy.git
        dest: /home/issam/cloud_1

    - name: Create Data folder for volumes if not exist
      ansible.builtin.file:
        path: /home/issam/data
        owner: issam
        group: issam
        state: directory
        mode: '0755'

    - name: Create Data folder for volumes if not exist
      ansible.builtin.file:
        path: /home/issam/data/DB
        owner: issam
        group: issam
        state: directory
        mode: '0755'

    - name: Create Data folder for volumes if not exist
      ansible.builtin.file:
        path: /home/issam/data/WordPress
        owner: issam
        group: issam
        state: directory
        mode: '0755'

    - name: Execute run script to deploy wp docker containers
      shell:
        chdir: /home/issam/cloud_1/wordpress/
        cmd: "docker-compose up -d --build"

- name: Deny SSH
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Create Network Security Group that Denys SSH (NSG)
    azure_rm_securitygroup:
      resource_group: "{{ WordPressResourceGroupName }}"
      name: "{{ WP_NSGName }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Deny
          priority: 1001
          direction: Inbound