# https://www.redhat.com/sysadmin/container-images-ansible
---
- hosts: [docker]
  gather_facts: no
  become: yes
  tasks:

  # - name: Copy MySQL Dockerfile From AnsibleMaster to WPVM
  #   copy: src=/home/issam/playbooks/mysql/Dockerfile dest=/home/issam/mysql/Dockerfile

  - name: Deploy MariaDB DataBase
    docker_container:
      image: mariadb
      name: mariadb
      volumes:
        - "mariadb:/var/lib/mysql"
      env:
        MYSQL_ROOT_PASSWORD: somerootpassword
        MYSQL_PASSWORD: somemysqlpassword
        MYSQL_DATABASE: db
        MYSQL_USER: mysqluser

  - name: Log into DockerHub
    docker_login:
      username: issamelferkh
      password: SNV@issam123
      email: issam.elferkh@gmail.com

  - name: Create Wordpress directory in WPVM
    file:
      path: /home/issam/wordpress
      state: directory
      owner: issam
      mode: 0775

  - name: Copy Wordpress Dockerfile From AnsibleMaster to WPVM
    copy: 
      src: /home/issam/playbooks/wordpress/Dockerfile
      dest: /home/issam/wordpress/Dockerfile
      owner: issam
      mode: 0775

  - name: Build Wordpress Image from Dockerfile
    docker_image:
      name: mywordpress:v1.1
      build:
        pull: yes
        path: /home/issam/wordpress/
      state: present
      source: build

  - name: Tag and push to docker hub
    docker_image:
      name: mywordpress:v1.1
      repository: issamelferkh/mywordpress:v1.1
      push: yes
      source: local

  - name: Deploy Wordpress Container
    docker_container:
      image: issamelferkh/mywordpress:v1.1
      name: mywordpress
      state: started
      restart_policy: always
      ports:
      - "8080:80"
      links:
        - "mariadb:/docker-entrypoint-initdb.d"
      volumes:
        - "www:/var/www/html"
      env:
        MYSQL_PASSWORD: somemysqlpassword
        MYSQL_DATABASE: db
        MYSQL_USER: mysqluser
        MYSQL_HOST: mariadb

  #     env:
  #       MYSQL_PASSWORD: somemysqlpassword
  #       MYSQL_DATABASE: db
  #       MYSQL_USER: mysqluser
  #       MYSQL_HOST: mysql
        # WORDPRESS_DB_HOST: mysql
        # WORDPRESS_DB_USER: exampleuser
        # WORDPRESS_DB_PASSWORD: Examplepass123!
        # WORDPRESS_DB_NAME: db