# https://markontech.com/ansible/deploy-wordpress-on-docker-using-ansible/
---
- hosts: [docker]
  gather_facts: no
  become: yes
  # vars:
  #   db_volume: mariadb
  #   wordpress: wordpress
  tasks:
    - name: Deploy MariaDB server
      docker_container:
        image: mariadb
        name: mariadb
        volumes:
          - "mariadb:/var/lib/mysql"
        env:
          MYSQL_ROOT_PASSWORD: issam123!
          MYSQL_PASSWORD: issam123!
          MYSQL_DATABASE: wordpressdb
          MYSQL_USER: issam

    - name: Deploy WordPress
      docker_container:
        image: wordpress
        name: wordpress
        restart_policy: always
        ports:
          - "8080:80"
        links:
          - "mariadb:/docker-entrypoint-initdb.d"
        volumes:
          - "wordpress:/var/www/html"
        env:
          WORDPRESS_DB_HOST: mariadb
          WORDPRESS_DB_USER: issam
          WORDPRESS_DB_PASSWORD: issam123!
          WORDPRESS_DB_NAME: wordpressdb

