- name: Create WordPress App
  hosts: localhost
  tasks:
  
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: myResourceGroup
      location: westus

  - name: Create sample container group
    azure_rm_containerinstance:
      resource_group: myResourceGroup
      name: mycontainerinstanceGroup
      os_type: linux
      ip_address: public
      containers:
        - name: mycontainer
          image: httpd
          memory: 1.5
          ports:
            - 80
            - 81
          volume_mounts:
            - name: myvolume1
              mount_path: "/mnt/test"
      volumes:
        - name: myvolume1
          git_repo:
            repository: "https://github.com/Azure-Samples/aci-helloworld.git"




  # - name: Create a linux app service plan
  #   azure_rm_appserviceplan:
  #     resource_group: myResourceGroup
  #     name: myAppServicePlan
  #     location: westus
  #     sku: S1
  #     is_linux: true
  #     number_of_workers: 1
      
  # - name: Create a multi-container web app
  #   azure_rm_webapp:
  #     resource_group: myResourceGroup
  #     name: myMultiContainerWebapp
  #     plan: myAppServicePlan
  #     app_settings:
  #       testkey: testvalue
  #     container_settings:
  #       name: "COMPOSE|{{ lookup('file', 'docker-compose-wordpress.yml') | b64encode }}"

# - name: Delete a resource group
#   azure_rm_resourcegroup:
#     name: myResourceGroup
#     state: absent

# - name: Delete a resource group including resources it contains
#   azure_rm_resourcegroup:
#     name: myResourceGroup
#     force_delete_nonempty: yes
#     state: absent





